### ISSUE TITLE
Script Evaluation Error

### ISSUE THREAD

**Issue by zzv2** [nline/nline-plotlyjs-panel#39]
![image](https://github.com/user-attachments/assets/811477e3-e501-48e4-a494-04ec899c2019)

We keep seeing these errors now when the query we have returns no data (empty set) for the time period we have selected.

**Comment by jacksongoode** [comment]
How is fields being set on line 8? A little bit of your script would help me debug :)

**Comment by zzv2** [comment]
```
let startName = data.series[0].fields[0].values;
```

**Comment by zzv2** [comment]
@jacksongoode upon further investigation I don't think its a huge issue since we could handle the no data case in the script by checking first:
```
  startName = data.series[0];
  if (!startName) {
    return {};
  }
  ```
however it might be good to consider if there should be some kind of default behavior in the case of no data like there is for other grafana panel types

**Comment by jacksongoode** [comment]
Yeah there actually is a check for when there is no data returned from the query. The checks are 1. if data itself is empty or if 2. there is one existing series that contains some amount of data. Do you have another query that has some data?

**Comment by jacksongoode** [comment]
I will say its a little tricky because if folks wanted to fabricate all the data from JS alone (and keep the Grafana query empty) then we want them to be able to. If we pre-exclude the script from being run because there is no data in a query then that wouldn't be possible. Right now we only check for no data after the script has been evaluated. So yes, if there's a case where your plot could have no data, then a simple early empty return is a good practice!

I'll add a note about this!

**Comment by zzv2** [comment]
That's a good point! Might be good to leave it up to the user but add a note. Thanks for taking the time to look into this :)
